
# Copyright (c) 2017-2024 King Abdullah University of Science and Technology,
# All rights reserved.
# VecchiaGB is a software package, provided by STSDS group at King Abdullah University of Science and Technology (KAUST).

# @file Makefile
# @brief Makefile for custom building Vecchia
# @version 1.0.0
# @author Sohayla Abouzeid
# @date 2025-01-XX

# This file is added to let R CMD build with Custom build configuration instead of using its
# main build system. The library is already built by CMake and copied to src/Vecchia.so
# by the configure script, so R doesn't need to compile anything.
all :

